### ISSUE TITLE
Exception when run from the first line in a block comment

### ISSUE THREAD

**Issue by FichteFoll** [ehuss/Sublime-Wrap-Plus#38]
With a comment as follows (and empty file), running wrap plus from the first comment line results in an exception. (Syntax: C or Stylus)

``` c
/* first line
 * comment
 */
```

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3 Portable Beta\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "wrap_plus in C:\Program Files\Sublime Text 3 Portable Beta\Data\Installed Packages\Wrap Plus.sublime-package", line 609, in run
  File "wrap_plus in C:\Program Files\Sublime Text 3 Portable Beta\Data\Installed Packages\Wrap Plus.sublime-package", line 343, in _find_paragraphs
  File "wrap_plus in C:\Program Files\Sublime Text 3 Portable Beta\Data\Installed Packages\Wrap Plus.sublime-package", line 275, in _find_paragraph_start
  File "wrap_plus in C:\Program Files\Sublime Text 3 Portable Beta\Data\Installed Packages\Wrap Plus.sublime-package", line 252, in _is_paragraph_break
  File "wrap_plus in C:\Program Files\Sublime Text 3 Portable Beta\Data\Installed Packages\Wrap Plus.sublime-package", line 263, in _is_blank_line
TypeError: expected string or buffer
```

**Comment by jtwalters** [comment]
Workaround: Ensure your first line begins with `/**` instead of just `/*`

**Comment by FichteFoll** [comment]
It was just an example for reproduction.
