### ISSUE TITLE
Wrap Plus no longer works in Sublime Dev Build 4153

### ISSUE THREAD

**Issue by maxim** [ehuss/Sublime-Wrap-Plus#76]
Looks like word wrapping broke as of Sublime Dev build 4153. Here's the console output when I press my keyboard shortcut for wrapping:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "/Users/max/Library/Application Support/Sublime Text/Installed Packages/Wrap Plus.sublime-package/wrap_plus.py", line 686, in run
  File "/Users/max/Library/Application Support/Sublime Text/Installed Packages/Wrap Plus.sublime-package/wrap_plus.py", line 396, in _find_paragraphs
  File "/Users/max/Library/Application Support/Sublime Text/Installed Packages/Wrap Plus.sublime-package/wrap_plus.py", line 100, in set_comments
ValueError: too many values to unpack (expected 2)
```

**Comment by deathaxe** [comment]
The plugin uses `Default.comment` module, which has been updated in ST4153 to support `TM_COMMENT_CASE_INSENSITIVE` variable, which fixes https://github.com/sublimehq/sublime_text/issues/6001.

As a result the data structure returned by `Default.comment.build_comment_data()` has changed.

Default modules are not necessarily part of ST's API and shouldn't be considered stable.
